app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    use HasFactory;
    protected $table = "media";
    public function getImageAttribute()
    {
        if($this->thumbnail){
            return asset('storage/' . $this->thumbnail);
        }else{
            return asset('keenthemes/media/avatars/blank.png');
        }
    }
}

app/Http/Controllers/Eproc/ProfileController.php
<?php

namespace App\Http\Controllers\Eproc;

use App\Models\Bank;
use App\Models\Kbli;
use App\Models\Partner;
use App\Models\Province;
use App\Models\PartnerDoc;
use App\Models\PartnerType;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Mail\PasswordChangedMail;
use App\Http\Controllers\Controller;
use App\Models\DocType;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class ProfileController extends Controller
{
    public function index(){
        return view('page.eproc.profile.main');
    }
    public function index_profile(){
        $remove1 = Str::remove('[',Auth::guard('procurement')->user()->bidang_usaha);
        $remove2 = Str::remove('"',$remove1);
        $remove3 = Str::remove(']',$remove2);
        $mykbli = explode(',',$remove3);
        $jenis_rekanan = PartnerType::get();
        $kbli = Kbli::orderBy('kode','ASC')->get();
        return view('page.eproc.profile.edit', compact('kbli','mykbli','jenis_rekanan'));
    }
    public function index_domisili(){
        $province = Province::get();
        return view('page.eproc.profile.edit_domisili',compact('province'));
    }
    public function index_bank(){
        $bank = Bank::orderBy('nama','ASC')->get();
        return view('page.eproc.profile.edit_bank',compact('bank'));
    }
    public function index_document(Request $request){
        $jenis = DocType::get();
        if ($request->ajax()) {
            $dokumen = PartnerDoc::where('partner_id', '=', Auth::guard('procurement')->user()->id)->paginate(10);
            return view('page.eproc.profile.list_doc',compact('dokumen'));
        }
        return view('page.eproc.profile.edit_document',compact('jenis'));
    }
    public function index_password(){
        return view('page.eproc.profile.edit_password');
    }
    public function change_profile(Request $request){
        $validator = Validator::make($request->all(), [
            'email' => 'required|email',
            'hp' => 'required',
            'bidang_usaha' => 'required',
            'jenis_rekanan' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }elseif ($errors->has('hp')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('hp'),
                ]);
            }elseif ($errors->has('bidang_usaha')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('bidang_usaha'),
                ]);
            }elseif ($errors->has('jenis_rekanan')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('jenis_rekanan'),
                ]);
            }
        }
        $partner = Partner::where('id','=',Auth::guard('procurement')->user()->id)->first();
        $partner->email = $request->email;
        $partner->hp = $request->hp;
        $partner->bidang_usaha = $request->bidang_usaha;
        $partner->partner_type_id = $request->jenis_rekanan;
        if(request()->file('avatar')){
            Storage::delete($partner->avatar);
            $avatar = request()->file('avatar')->store("avatar");
            $partner->avatar = $avatar;
        };
        $partner->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Profil tersimpan',
            'redirect' => 'reload',
        ]);
    }
    public function change_domisili(Request $request){
        $validator = Validator::make($request->all(), [
            'province' => 'required',
            'city' => 'required',
            'subdistrict' => 'required',
            'alamat' => 'required',
            'kode_pos' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('province')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('province'),
                ]);
            }elseif ($errors->has('city')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('city'),
                ]);
            }elseif ($errors->has('subdistrict')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('subdistrict'),
                ]);
            }elseif ($errors->has('alamat')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('alamat'),
                ]);
            }elseif ($errors->has('kode_pos')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('kode_pos'),
                ]);
            }
        }
        $partner = Partner::where('id','=',Auth::guard('procurement')->user()->id)->first();
        $partner->province_id = $request->province;
        $partner->city_id = $request->city;
        $partner->subdistrict_id = $request->subdistrict;
        $partner->alamat = $request->alamat;
        $partner->postcode = $request->kode_pos;
        $partner->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Domisili tersimpan',
            'redirect' => 'reload',
        ]);
    }
    public function change_bank(Request $request){
        $validator = Validator::make($request->all(), [
            'bank' => 'required',
            'no_rekening' => 'required',
            'atas_nama_rekening' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('bank')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('bank'),
                ]);
            }elseif ($errors->has('no_rekening')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('no_rekening'),
                ]);
            }elseif ($errors->has('atas_nama_rekening')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('atas_nama_rekening'),
                ]);
            }
        }
        $partner = Partner::where('id','=',Auth::guard('procurement')->user()->id)->first();
        $partner->bank_id = $request->bank;
        $partner->no_rek = $request->no_rekening;
        $partner->rek_an = $request->atas_nama_rekening;
        $partner->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Bank tersimpan',
            'redirect' => 'reload',
        ]);
    }
    public function change_document(Request $request){
        $validator = Validator::make($request->all(), [
            'nama_pendiri' => 'required',
            'no_ktp' => 'required',
            'no_npwp' => 'required',
            // 'compro' => 'mimes:pdf',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('nama_pendiri')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('nama_pendiri'),
                ]);
            }elseif ($errors->has('no_ktp')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('no_ktp'),
                ]);
            }elseif ($errors->has('no_npwp')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('no_npwp'),
                ]);
            }
        }
        $partner = Partner::where('id','=',Auth::guard('procurement')->user()->id)->first();
        $partner->nama_pendiri = $request->nama_pendiri;
        $partner->no_ktp = $request->no_ktp;
        $partner->no_npwp = $request->no_npwp;
        $partner->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Dokumen tersimpan',
            'redirect' => 'reload',
        ]);
    }
    public function change_password(Request $request){
        $validator = Validator::make($request->all(), [
            'password' => 'required|string|min:8|confirmed',
            'password_confirmation' => 'required'
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            } elseif ($errors->has('password_confirmation')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password_confirmation'),
                ]);
            }
        }
        Partner::where('id', Auth::guard('procurement')->user()->id)->update(['password' => Hash::make($request->password)]);
        $users = Partner::where('id', Auth::guard('procurement')->user()->id)->first();
        Mail::to($users->email)->send(new PasswordChangedMail($users));
        return response()->json([
            'alert' => 'success',
            'message' => 'Kata sandi tersimpan',
            'redirect' => 'reload',
        ]);
    }

app/Http/Controllers/Office/AuthController.php
<?php

namespace App\Http\Controllers\Office;

use App\Models\Employee;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use App\Mail\PasswordChangedMail;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;
use App\Mail\ConfirmationResetPasswordMail;

class AuthController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest:office')->except('do_logout');
    }
    public function index()
    {
        return view('page.office.auth.main');
    }
    public function do_login(Request $request){
        $validator = Validator::make($request->all(), [
            'email' => 'required|exists:employee|email|max:255',
            'password' => 'required|min:8',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            }
        }
        if(Auth::guard('office')->attempt(['email' => $request->email, 'password' => $request->password], $request->remember))
        {
            return response()->json([
                'alert' => 'success',
                'message' => 'Selamat datang '. Auth::guard('office')->user()->nama,
                'callback' => 'reload',
            ]);
        }else{
            return response()->json([
                'alert' => 'error',
                'message' => 'Maaf, sepertinya ada beberapa kesalahan yang terdeteksi, silakan coba lagi.',
            ]);
        }
    }
    public function do_forgot(Request $request){
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|exists:employee',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }
        }
        $employee = Employee::where('email',$request->email)->first();

        $token = Str::random(64);
        DB::table('password_resets')->insert([
            'email' => $request->email,
            'token' => $token,
            'created_at' => Carbon::now()
        ]);
        $data = array(
            'token' => $token,
            'employee' => $employee
        );
        Mail::to($request->email)->send(new ConfirmationResetPasswordMail($data));
        return response()->json([
            'alert' => 'success',
            'message' => 'Kami telah mengirim email tautan pemulihan kata sandi Anda!',
            'callback' => 'page_login',
        ]);
    }
    public function reset($token){
        $updatePassword = DB::table('password_resets')->where(['token' => $token])->first();
        if (!$updatePassword) {
            return redirect()->route('auth.index');
        }else{
            return view('page.office.auth.reset', compact('token'));
        }
    }
    public function do_reset(Request $request){
        $validator = Validator::make($request->all(), [
            'token' => 'required|exists:password_resets',
            'password' => 'required|string|min:8|confirmed',
            'password_confirmation' => 'required'
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('token')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('token'),
                ]);
            } elseif ($errors->has('password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            } elseif ($errors->has('password_confirmation')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password_confirmation'),
                ]);
            }
        }
        $updatePassword = DB::table('password_resets')->where(['token' => $request->token])->first();
        if (!$updatePassword) {
            return response()->json([
                'alert' => 'error',
                'message' => 'Invalid token!',
            ]);
        }
        Employee::where('email', $updatePassword->email)->update(['password' => Hash::make($request->password)]);
        $users = Employee::where('email', $updatePassword->email)->first();
        DB::table('password_resets')->where(['email' => $updatePassword->email])->delete();
        Mail::to($users->email)->send(new PasswordChangedMail($users));
        return response()->json([
            'alert' => 'success',
            'message' => 'Kata sandi Anda telah diubah!',
            'callback' => 'reload',
        ]);
    }
    public function do_logout(){
        $user = Auth::guard('office')->user();
        Auth::logout($user);
        return redirect()->route('office.auth.index');
    }
}

app/Http/Controllers/Office/DashboardController.php
<?php

namespace App\Http\Controllers\Office;

use App\Models\Tender;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $publikasi = Tender::with('list_penawaran')->where('st','=','Terpublikasi')->get();
        $nilai = 0;
        foreach ($publikasi as $pub){
            $nilai += $pub->list_penawaran->sum('nilai');
        }
        $berjalan = Tender::where('st','=','Berjalan')->with('list_penawaran')->get();
        $selesai = Tender::where('st','=','Selesai')->with('list_penawaran')->get();
        return view('page.office.dashboard.main',compact('publikasi','nilai','berjalan','selesai'));
    }
}

app/Http/Controllers/Office/KarirController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use App\Models\Karir;
use Illuminate\Http\Request;

class KarirController extends Controller
{
    public function index()
    {
        //
    }
    public function create()
    {
        //
    }
    public function store(Request $request)
    {
        //
    }
    public function show(Karir $karir)
    {
        //
    }
    public function edit(Karir $karir)
    {
        //
    }
    public function update(Request $request, Karir $karir)
    {
        //
    }
    public function destroy(Karir $karir)
    {
        //
    }
}

app/Http/Controllers/Office/Pengadaan/PartnerDocController.php
<?php

namespace App\Http\Controllers\Office\Pengadaan;

use App\Models\PartnerDoc;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class PartnerDocController extends Controller
{
    public function download(PartnerDoc $partnerDoc)
    {
        return Storage::download($partnerDoc->file);
    }
}

resources/views/page/office/profile/edit.blade.php
<x-office-layout title="Edit Profil">
    <div class="toolbar d-flex flex-stack mb-3 mb-lg-5" id="kt_toolbar">
        <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack flex-wrap">
            <div class="page-title d-flex flex-column me-5 py-2">
                <h1 class="d-flex flex-column text-dark fw-bolder fs-3 mb-0">Edit Profil</h1>
                <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 pt-1">
                    <li class="breadcrumb-item text-muted">
                        <a href="{{route('office.dashboard')}}" class="text-muted text-hover-primary">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <span class="bullet bg-gray-200 w-5px h-2px"></span>
                    </li>
                    <li class="breadcrumb-item text-muted">Edit Profil</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <div id="kt_content_container" class="container-xxl">
            <div class="card mb-5 mb-xxl-8">
                <div class="card-body pt-9 pb-0">
                    <div class="d-flex flex-wrap flex-sm-nowrap">
                        <div class="me-7 mb-4">
                            <div class="symbol symbol-100px symbol-lg-160px symbol-fixed position-relative">
                                <img src="{{Auth::guard('office')->user()->image}}" alt="image" />
                                <div class="position-absolute translate-middle bottom-0 start-100 mb-6 bg-success rounded-circle border border-4 border-white h-20px w-20px"></div>
                            </div>
                        </div>
                        <div class="flex-grow-1">
                            <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                                <div class="d-flex flex-column">
                                    <div class="d-flex align-items-center mb-2">
                                        <a href="javascript:;" class="text-gray-900 text-hover-primary fs-2 fw-bolder me-1">
                                            {{Auth::guard('office')->user()->nama}}
                                        </a>
                                        <a href="javascript:;">
                                            <span class="svg-icon svg-icon-1 svg-icon-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
                                                    <path d="M10.0813 3.7242C10.8849 2.16438 13.1151 2.16438 13.9187 3.7242V3.7242C14.4016 4.66147 15.4909 5.1127 16.4951 4.79139V4.79139C18.1663 4.25668 19.7433 5.83365 19.2086 7.50485V7.50485C18.8873 8.50905 19.3385 9.59842 20.2758 10.0813V10.0813C21.8356 10.8849 21.8356 13.1151 20.2758 13.9187V13.9187C19.3385 14.4016 18.8873 15.491 19.2086 16.4951V16.4951C19.7433 18.1663 18.1663 19.7433 16.4951 19.2086V19.2086C15.491 18.8873 14.4016 19.3385 13.9187 20.2758V20.2758C13.1151 21.8356 10.8849 21.8356 10.0813 20.2758V20.2758C9.59842 19.3385 8.50905 18.8873 7.50485 19.2086V19.2086C5.83365 19.7433 4.25668 18.1663 4.79139 16.4951V16.4951C5.1127 15.491 4.66147 14.4016 3.7242 13.9187V13.9187C2.16438 13.1151 2.16438 10.8849 3.7242 10.0813V10.0813C4.66147 9.59842 5.1127 8.50905 4.79139 7.50485V7.50485C4.25668 5.83365 5.83365 4.25668 7.50485 4.79139V4.79139C8.50905 5.1127 9.59842 4.66147 10.0813 3.7242V3.7242Z" fill="#00A3FF" />
                                                    <path class="permanent" d="M14.8563 9.1903C15.0606 8.94984 15.3771 8.9385 15.6175 9.14289C15.858 9.34728 15.8229 9.66433 15.6185 9.9048L11.863 14.6558C11.6554 14.9001 11.2876 14.9258 11.048 14.7128L8.47656 12.4271C8.24068 12.2174 8.21944 11.8563 8.42911 11.6204C8.63877 11.3845 8.99996 11.3633 9.23583 11.5729L11.3706 13.4705L14.8563 9.1903Z" fill="white" />
                                                </svg>
                                            </span>
                                        </a>
                                    </div>
                                    <div class="d-flex flex-wrap fw-bold fs-6 mb-4 pe-2">
                                        <a href="javascript:;" class="d-flex align-items-center text-gray-400 text-hover-primary me-5 mb-2">
                                            <span class="svg-icon svg-icon-4 me-1">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                    <path opacity="0.3" d="M22 12C22 17.5 17.5 22 12 22C6.5 22 2 17.5 2 12C2 6.5 6.5 2 12 2C17.5 2 22 6.5 22 12ZM12 7C10.3 7 9 8.3 9 10C9 11.7 10.3 13 12 13C13.7 13 15 11.7 15 10C15 8.3 13.7 7 12 7Z" fill="black" />
                                                    <path d="M12 22C14.6 22 17 21 18.7 19.4C17.9 16.9 15.2 15 12 15C8.8 15 6.09999 16.9 5.29999 19.4C6.99999 21 9.4 22 12 22Z" fill="black" />
                                                </svg>
                                            </span>
                                            {{Auth::guard('office')->user()->lokasi->nama}} - {{Auth::guard('office')->user()->divisi->nama}} - {{Auth::guard('office')->user()->role->nama}}
                                        </a>
                                        @if(Auth::guard('office')->user()->alamat)
                                        <a href="javascript:;" class="d-flex align-items-center text-gray-400 text-hover-primary me-5 mb-2">
                                            <span class="svg-icon svg-icon-4 me-1">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                    <path opacity="0.3" d="M18.0624 15.3453L13.1624 20.7453C12.5624 21.4453 11.5624 21.4453 10.9624 20.7453L6.06242 15.3453C4.56242 13.6453 3.76242 11.4453 4.06242 8.94534C4.56242 5.34534 7.46242 2.44534 11.0624 2.04534C15.8624 1.54534 19.9624 5.24534 19.9624 9.94534C20.0624 12.0453 19.2624 13.9453 18.0624 15.3453Z" fill="black" />
                                                    <path d="M12.0624 13.0453C13.7193 13.0453 15.0624 11.7022 15.0624 10.0453C15.0624 8.38849 13.7193 7.04535 12.0624 7.04535C10.4056 7.04535 9.06241 8.38849 9.06241 10.0453C9.06241 11.7022 10.4056 13.0453 12.0624 13.0453Z" fill="black" />
                                                </svg>
                                            </span>
                                            {{Auth::guard('office')->user()->alamat}}
                                        </a>
                                        @endif
                                        <a href="javascript:;" class="d-flex align-items-center text-gray-400 text-hover-primary mb-2">
                                            <span class="svg-icon svg-icon-4 me-1">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                    <path opacity="0.3" d="M21 19H3C2.4 19 2 18.6 2 18V6C2 5.4 2.4 5 3 5H21C21.6 5 22 5.4 22 6V18C22 18.6 21.6 19 21 19Z" fill="black" />
                                                    <path d="M21 5H2.99999C2.69999 5 2.49999 5.10005 2.29999 5.30005L11.2 13.3C11.7 13.7 12.4 13.7 12.8 13.3L21.7 5.30005C21.5 5.10005 21.3 5 21 5Z" fill="black" />
                                                </svg>
                                            </span>
                                            {{Auth::guard('office')->user()->email}}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ul class="nav nav-stretch nav-line-tabs nav-line-tabs-2x border-transparent fs-5 fw-bolder">
                        <li class="nav-item mt-2">
                            <a class="nav-link text-active-primary ms-0 me-10 py-5" href="{{route('office.profile.index')}}">Preview</a>
                        </li>
                        <li class="nav-item mt-2">
                            <a class="nav-link text-active-primary ms-0 me-10 py-5 active" href="{{route('office.profile.edit')}}">Pengaturan Akun</a>
                        </li>
                        <li class="nav-item mt-2">
                            <a class="nav-link text-active-primary ms-0 me-10 py-5" href="{{route('office.profile.edit_password')}}">Keamanan</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="content_input">
                <div class="row g-5 g-xxl-8">
                    <div class="col-xl-12">
                        <div class="card mb-5 mb-xxl-8">
                            <div class="card-body pb-0">
                                <form id="form_input">
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <label class="fs-6 fw-bold mb-2">Nama</label>
                                            <input type="text" class="form-control" readonly value="{{Auth::guard('office')->user()->nama}}">
                                        </div>
                                        <div class="col-lg-4">
                                            <label class="fs-6 fw-bold mb-2">NIP</label>
                                            <input type="text" class="form-control" readonly value="{{Auth::guard('office')->user()->nip}}">
                                        </div>
                                        <div class="col-lg-4">
                                            <label class="fs-6 fw-bold mb-2">Avatar</label>
                                            <input type="file" name="avatar" class="form-control">
                                        </div>
                                        <div class="col-lg-6 mt-5">
                                            <label class="required fs-6 fw-bold mb-2">Email</label>
                                            <input type="email" name="email" class="form-control" value="{{Auth::guard('office')->user()->email}}">
                                        </div>
                                        <div class="col-lg-6 mt-5">
                                            <label class="required fs-6 fw-bold mb-2">No HP</label>
                                            <input type="tel" maxlength="13" name="hp" class="form-control" value="{{Auth::guard('office')->user()->hp}}">
                                        </div>
                                        <div class="min-w-150px mt-10 text-end">
                                            <button id="tombol_simpan" onclick="handle_upload('#tombol_simpan','#form_input','{{route('office.profile.change')}}','POST');" class="btn btn-sm btn-success">Simpan</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-office-layout>